const SHEET_CSV_URL="https://docs.google.com/spreadsheets/d/1GVwiEQIg2snbVJqzNBBG1VmXhJdWnANgXRDF21ekDvU/export?format=csv&gid=330320146";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let OWNED=[];
function csv(t){let a=[],r=[],c="",q=false;for(let i=0;i<t.length;i++){let x=t[i];if(x=='"'){if(q&&t[i+1]=='"'){c+='"';i++}else q=!q}else if(x==','&&!q){r.push(c);c=""}else if((x=='\n'||x=='\r')&&!q){if(x=='\r'&&t[i+1]=='\n')i++;r.push(c);c="";if(r.some(Boolean))a.push(r);r=[]}else c+=x}r.push(c);if(r.some(Boolean))a.push(r);let h=a.shift()||[];return a.map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]||""])))}
const split=s=>(s||"").split(";").map(x=>x.trim()).filter(Boolean);
function card(g){let im=g.cover||"",u=g.name==="Bomb Busters"?"missioni":"partite",ty=g.type==="expansion"?" · Espansione":g.type==="standalone"?" · Stand-alone":"";return `<button class="card game" data-game="${g.name.replaceAll('"',"&quot;")}"><div class="cover" style="${im?`background-image:url('${im}')`:""}">${im?"":"🎲"}</div><div class="txt"><b>${g.name}</b><div class="muted">${g.plays||0} ${u}${ty}</div></div></button>`}
function render(rows){let p={},cnt={};for(const r of rows){let g=r["Gioco"];if(g)cnt[g]=(cnt[g]||0)+1;for(const n of split(r["Giocatori"])){p[n]??={name:n,plays:0,wins:0};p[n].plays++}for(const n of split(r["Vincitore/i"])){p[n]??={name:n,plays:0,wins:0};p[n].wins++}}let ps=Object.values(p).sort((a,b)=>b.wins-a.wins||b.plays-a.plays),gs=OWNED.map(g=>({...g,plays:cnt[g.name]||0})),played=gs.filter(g=>g.plays).sort((a,b)=>b.plays-a.plays);$("#total").textContent=`${rows.length} partite`;$("#metrics").innerHTML=`<div class="card metric"><span class="muted">Partite</span><b>${rows.length}</b></div><div class="card metric"><span class="muted">Collezione</span><b>${OWNED.filter(g=>g.type!=="expansion").length}</b></div><div class="card metric"><span class="muted">Giochi giocati</span><b>${played.length}</b></div><div class="card metric"><span class="muted">Giocatori</span><b>${ps.length}</b></div>`;$("#ranking").innerHTML=ps.map((x,i)=>`<div class="row"><b>${i+1}.</b><div class="grow"><b>${x.name}</b><div class="muted">${x.plays} giocate · ${x.wins} vittorie</div></div><span class="badge">${x.plays?(x.wins/x.plays*100).toFixed(0):0}%</span></div>`).join("");$("#topgames").innerHTML=(played.length?played:gs).slice(0,4).map(card).join("");$("#allgames").innerHTML=gs.map(card).join("");$("#playerlist").innerHTML=ps.map(x=>`<div class="row"><div class="grow"><b>${x.name}</b><div class="muted">${x.plays} giocate</div></div><b>${x.wins} 🏆</b></div>`).join("");$("#historylist").innerHTML=[...rows].reverse().slice(0,60).map(r=>`<div class="row"><div class="grow"><b>${r["Gioco"]||""}</b><div class="muted">${r["Data"]||""}</div></div><b>${r["Vincitore/i"]||""}</b></div>`).join("")}
async function start(){try{OWNED=await fetch("./collection.json?v=33",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("collection");return r.json()});let r=await fetch(SHEET_CSV_URL,{cache:"no-store"});if(!r.ok)throw Error("sheet");let rows=csv(await r.text());if(!rows.length||!("Gioco" in rows[0]))throw Error("csv");$("#status").textContent="DATI LIVE · build v3.3";render(rows)}catch(e){console.error(e);$("#status").textContent="ERRORE DATI · build v3.3";$("#total").textContent="Errore"}}
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.toggle("active",x===b));["home","games","players","history","detail"].forEach(v=>$("#"+v).classList.toggle("hidden",v!==b.dataset.v))});
document.addEventListener("click",e=>{let b=e.target.closest("[data-game]");if(!b)return;$("#detailbody").innerHTML=`<div class="card"><h2>${b.dataset.game}</h2><p class="muted">Dettaglio gioco · build v3.3</p></div>`;["home","games","players","history"].forEach(v=>$("#"+v).classList.add("hidden"));$("#detail").classList.remove("hidden")});
$("#back").onclick=()=>{$("#detail").classList.add("hidden");$("#games").classList.remove("hidden")};start();